from colorama import Back,Fore
print(Back.BLUE , Fore.LIGHTGREEN_EX)
print("            ****            ")
print("        ***      ***          ")
print("      **           **         ")
print("     **             **       " )
print("    **               **       ")
print("    *                 *      ")
print ("   *                 *   " )         
print ("   *                 *    " )
print ("    **              **   " )
print ("      **          **    " )
print ("       **  **** **    " )
print ("            ****    " )