from colorama import Back,Fore
print("**********************************************")
print("*                                             *")
print("*                                             *")
print("*                                             *")
print("*                                             *")
print("***********************************************")

print( Back. LIGHTYELLOW_EX , Fore. BLACK)
print("                    *                          ")
print("                  *   *                        ")
print("                 *     *                      ")
print("                *       *                    ")
print("               *         *                 " )          
print("              *************                ")

print( Back. LIGHTYELLOW_EX , Fore. BLACK)
print("                   ****************************                      ")
print("                 *                          *")
print("               *                          *")
print("             *                          *")
print("           *                          *")
print("         *                          *")
print("       *                          *")
print("     ****************************                      ")